runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  BUCKET_UPLOAD: 'upload.executivetraveller.com'
  BUCKET_IMAGES: 'images.executivetraveller.com'
  BUCKET_FILES: 'files.executivetraveller.com'

libraries:
- name: ssl
  version: latest

handlers:
  - url: /(.*\.(gif|png|jpg|jpeg|webp))$
    script: main.app
  - url: .*
    static_dir: static
    